name: Merge upstream branches

on:
  schedule:
    - cron:  '*/10 * * * *'
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge upstream
        run: |
          git config --global user.name 'ShinyGil'
          git config --global user.email 'rockgrub@protonmail.com'
          git config --global merge.ours.driver true

          
          git pull --unshallow
                               
                                
                                

          git remote add upstream https://github.com/terrapkg/packages
          git fetch upstream f40



          

          git checkout f40
          git merge --no-edit upstream/f40
          git push origin f40
